"""Add OTP fields to User model

Revision ID: f3a4ffc4c7f1
Revises: 5a0f48fdae2e
Create Date: 2025-05-14 04:44:28.342312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a4ffc4c7f1'
down_revision = '5a0f48fdae2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_attempts')
        batch_op.drop_column('otp_created_at')

    # ### end Alembic commands ###
